repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -  id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      args:
        - --line-length=120
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: 'isort (for messenger)'
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: ["--max-line-length", "120"]
        exclude: /migrations/
