services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh fastapi-entrypoint.sh
    env_file:
      - backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend

