# Generated by Django 4.2.1 on 2023-05-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passwords", "0002_auto_20230506_0702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passwords",
                to="passwords.passwordcategory",
            ),
        ),
        migrations.AlterField(
            model_name="password",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="passwordcategory",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
