# Generated by Django 4.2.1 on 2023-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passwords", "0003_alter_password_category_alter_password_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
